/*++

Copyright (C) 2026 3MF Consortium

All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice,
this list of conditions and the following disclaimer in the documentation
and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

--*/

#ifndef __TOOLPATH_MATJOBCONST
#define __TOOLPATH_MATJOBCONST

#define MATJOB_3MFNAMESPACEDOUBLE "http://schemas.materialise.com/AM/MatJob/MetaDataDouble"
#define MATJOB_3MFNAMESPACEINTEGER "http://schemas.materialise.com/AM/MatJob/MetaDataInteger"

#define VECTORTYPEID_HATCH 0
#define VECTORTYPEID_BORDER 1

#define MATJOB_GROUP_HEADER 1
#define MATJOB_HEADER_SIGNATURE 10
#define MATJOB_HEADER_UNKNOWN_11 11
#define MATJOB_HEADER_FOLDER 12

#define MATJOB_GROUP_FILEDATA 2
#define MATJOB_GROUP_BEGINLAYER 21

#define MATJOB_GROUP_ZHEIGHT 210
#define MATJOB_GROUP_DATABLOCK 212

#define MATJOB_GROUP_DATABLOCKTYPE 2120
#define MATJOB_GROUP_DATABLOCKUNKNOWN2121 2121
#define MATJOB_GROUP_DATABLOCKUNKNOWN2122 2122
#define MATJOB_GROUP_DATABLOCKUNKNOWN2123 2123
#define MATJOB_GROUP_DATABLOCKPOINTS 2124

#define MATJOB_DATABLOCKTYPE_HATCHBLOCK 1
#define MATJOB_DATABLOCKTYPE_POLYLINELIST 3

#define MATJOB_MAXHATCHCOUNTPERBLOCK (1UL << 27)
#define MATJOB_MAXPOINTCOUNTPERPOLYLINE (1UL << 28)

#endif // __TOOLPATH_MATJOBCONST
